sudo: required
services:
    - docker

before_install: 
    - docker build -t mert5432100/docker-react -f Dockerfile.dev .

script: 
    - docker run -e CI=true mert5432100/docker-react npm run test


deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "react"
    env: "React-env"
    bucket_name: "elasticbeanstalk-us-east-1-913558582490"
    bucket_path: "react"
    on:
        branch: main
    access_key_id: $AWS_SECRET
    secret_access_key: $AWS_SECRET_ACCESS