sudo: required
services:
    - docker

before_install: 
    - docker build -t mert5432100/docker-react -f Dockerfile.dev .

script: 
    - docker run mert5432100/docker-react npm run test -- --coverage